manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 1493620bf76e05d8419ceec37681b69ca024a871
      import: app/west.yml
  self:
    path: config
