manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 313ed6adb6db3154c14f783b791255b6f3422fb3
      import: app/west.yml
  self:
    path: config
