manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 062f94d0144530fa699e5158b87293e7ebb526fc
      import: app/west.yml
  self:
    path: config
