manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 134b64ef5bbc67dd9f1c2a961609c62d4f226711
      import: app/west.yml
  self:
    path: config
