manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 518f9a550f5016dad4e8d96ed68f1c4e6a8ccb93
      import: app/west.yml
  self:
    path: config
