manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 243a227ff96e0cc25d4ae362efb30c769b4bc329
      import: app/west.yml
  self:
    path: config
