manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: a6ebdb7180f5b49d0603de91ca899ea789af0365
      import: app/west.yml
  self:
    path: config
