manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 31f664ffec0e90fe2123e1dfcaca4b34654d4714
      import: app/west.yml
  self:
    path: config
