manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 0c5bcf5fe4dff38f55219c213a745a6731544896
      import: app/west.yml
  self:
    path: config
