manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: c3d06b22c8b501fc69f6c2c140c10c95f989c76b
      import: app/west.yml
  self:
    path: config
