manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 198daaf524a2c1223393922195d8f1004964ae2e
      import: app/west.yml
  self:
    path: config
