manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 4f2f9db1d474dc8754780b27243b1a61acbdad42
      import: app/west.yml
  self:
    path: config
