manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: d513dc1766edf52a22d78da0e73d5a09670059e9
      import: app/west.yml
  self:
    path: config
