manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 69a4c3200d8c9c92e3e3c68bbd4969f19df70133
      import: app/west.yml
  self:
    path: config
