manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 2f9bc2f1f7b2ad0e0662ef53f5479b72c0f84d02
      import: app/west.yml
  self:
    path: config
