manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 35a1c5a3d44b92c050d28c0aca3d1cb9c7e53695
      import: app/west.yml
  self:
    path: config
